"""Type stubs for the Rust extension module (JSON in, JSON out)."""

def admit(wire: str) -> str: ...
def evaluate(wire: str, request: str) -> str: ...
def replay(wire: str, record: str) -> str: ...
def evaluate_intent(wire: str, intent: str, host: str) -> str: ...
