"""Type stubs for the Rust extension module (contracts/engine-api.md → Python binding)."""

class Node:
    @property
    def type_json(self) -> str | None: ...
    @property
    def role(self) -> str | None: ...

class Module:
    @staticmethod
    def from_wire(wire: str) -> tuple[Module | None, str]: ...
    @property
    def behavior_version(self) -> str: ...
    def admission_json(self) -> str: ...
    def wire_json(self) -> str: ...
    def evaluate(self, request: str) -> str: ...
    def evaluate_intent(self, intent: str, host: str) -> str: ...
    def replay(self, record: str) -> str: ...

class Builder:
    def __init__(self) -> None: ...
    def declare_enum(self, name: str, values: list[str], file: str, line: int) -> None: ...
    def declare_nominal(
        self, name: str, underlying_json: str, ops: list[str], file: str, line: int
    ) -> None: ...
    def declare_entity(self, name: str, fields_json: str, file: str, line: int) -> None: ...
    def push_scope(self, site: str, params_json: str, file: str, line: int) -> None: ...
    def pop_scope(self) -> None: ...
    def lit(self, type_json: str, value_json: str, file: str, line: int) -> Node: ...
    def field(self, param: str, field: str, file: str, line: int) -> Node: ...
    def param(self, name: str, file: str, line: int) -> Node: ...
    def derived_ref(self, name: str, args: list[str], file: str, line: int) -> Node: ...
    def op(self, op: str, args: list[Node], file: str, line: int) -> Node: ...
    def in_(self, arg: Node, values_json: str, file: str, line: int) -> Node: ...
    def wrap(self, nominal: str, arg: Node, file: str, line: int) -> Node: ...
    def check_condition(self, node: Node, what: str) -> None: ...
    def check_effect(self, param: str, field: str, value: Node) -> None: ...
    def add_derived(
        self, name: str, kind: str, params_json: str, body: Node, file: str, line: int
    ) -> None: ...
    def add_invariant(
        self, name: str, entity: str, param: str, body: Node, file: str, line: int
    ) -> None: ...
    def add_action(
        self,
        name: str,
        params_json: str,
        preconditions: list[tuple[Node, str, int]],
        effects: list[tuple[str, str, Node, str, int]],
        postconditions: list[tuple[Node, str, int]],
        file: str,
        line: int,
    ) -> None: ...
    def finish(self, root: str | None) -> tuple[Module | None, str]: ...
