"""Type stubs for the Rust extension module (contracts/engine-api.md → Python binding)."""

import builtins
from typing import Any

class EngineError(Exception): ...
class EngineIntentRejected(Exception): ...

class Type:
    @staticmethod
    def bool() -> Type: ...
    @staticmethod
    def int() -> Type: ...
    @staticmethod
    def decimal() -> Type: ...
    @staticmethod
    def string() -> Type: ...
    @staticmethod
    def option(of: Type) -> Type: ...
    @staticmethod
    def enum(name: str) -> Type: ...
    @staticmethod
    def nominal(name: str) -> Type: ...
    @staticmethod
    def exact(name: str | None = None) -> Type: ...
    @staticmethod
    def id(entity: str) -> Type: ...
    @staticmethod
    def entity(name: str) -> Type: ...
    def is_option(self) -> builtins.bool: ...
    def inner(self) -> Type | None: ...

class Node:
    @property
    def type(self) -> Type | None: ...
    @property
    def role(self) -> str | None: ...

class Record:
    @property
    def result(self) -> str: ...
    @property
    def data(self) -> dict[str, Any]: ...
    @property
    def json(self) -> str: ...

class Attestation:
    @property
    def result(self) -> str: ...
    @property
    def hash(self) -> str: ...
    @property
    def data(self) -> dict[str, Any]: ...
    @property
    def json(self) -> str: ...

class Authorization:
    @property
    def decision(self) -> str: ...
    @property
    def data(self) -> dict[str, Any]: ...
    @property
    def json(self) -> str: ...

def waiver_hash(waiver: dict[str, Any]) -> str: ...
def sign_waiver(waiver: dict[str, Any], seed: str) -> dict[str, Any]: ...

class Module:
    @staticmethod
    def from_wire(wire: str) -> tuple[Module | None, dict[str, Any]]: ...
    @property
    def behavior_version(self) -> str: ...
    def admission(self) -> dict[str, Any]: ...
    def wire_json(self) -> str: ...
    def evaluate(
        self,
        action: str,
        state: dict[str, Any],
        input: dict[str, Any],
        context: dict[str, Any],
        data_version: str,
        git_revision: str | None = None,
    ) -> Record: ...
    def evaluate_intent(
        self,
        intent: dict[str, Any],
        state: dict[str, Any],
        context: dict[str, Any],
        data_version: str,
        git_revision: str | None = None,
    ) -> Record: ...
    def replay(self, record_json: str) -> tuple[bool, str | None]: ...
    def authorize(
        self,
        policy: dict[str, Any],
        record_json: str,
        attestation_json: str | None,
        waivers: list[dict[str, Any]],
        signatures: list[dict[str, Any]],
        now: str,
    ) -> Authorization: ...
    def verify(
        self,
        checks: list[str] | None,
        rlimit: int,
        wall_clock_guard_ms: int,
        cache: str | None = None,
    ) -> Attestation: ...

Param = tuple[str, str | None, Type]

class Builder:
    def __init__(self) -> None: ...
    def declare_enum(self, name: str, values: list[str], file: str, line: int) -> None: ...
    def declare_nominal(
        self,
        name: str,
        underlying: Type,
        ops: list[str],
        file: str,
        line: int,
        scale: int | None = None,
    ) -> None: ...
    def declare_entity(
        self, name: str, fields: list[tuple[str, Type, str, int]], file: str, line: int
    ) -> None: ...
    def push_scope(self, site: str, params: list[Param], file: str, line: int) -> None: ...
    def pop_scope(self) -> None: ...
    def lit(self, type: Type, value: Any, file: str, line: int) -> Node: ...
    def field(self, param: str, field: str, file: str, line: int) -> Node: ...
    def param(self, name: str, file: str, line: int) -> Node: ...
    def derived_ref(self, name: str, args: list[str], file: str, line: int) -> Node: ...
    def op(self, op: str, args: list[Node], file: str, line: int) -> Node: ...
    def in_(self, arg: Node, values: list[Any], file: str, line: int) -> Node: ...
    def wrap(self, nominal: str, arg: Node, file: str, line: int) -> Node: ...
    def rescale(self, arg: Node, nominal: str, rounding: str, file: str, line: int) -> Node: ...
    def check_condition(self, node: Node, what: str) -> None: ...
    def check_effect(self, param: str, field: str, value: Node) -> None: ...
    def add_derived(
        self,
        name: str,
        kind: str,
        params: list[Param],
        body: Node,
        file: str,
        line: int,
        declared: Type | None = None,
    ) -> None: ...
    def add_invariant(
        self, name: str, entity: str, param: str, body: Node, file: str, line: int
    ) -> None: ...
    def add_constraint(
        self, name: str, entity: str, param: str, body: Node, file: str, line: int
    ) -> None: ...
    def add_action(
        self,
        name: str,
        params: list[Param],
        preconditions: list[tuple[Node, str, int]],
        effects: list[tuple[str, str, Node, str, int]],
        postconditions: list[tuple[Node, str, int]],
        file: str,
        line: int,
    ) -> None: ...
    def finish(self, root: str | None) -> tuple[Module | None, dict[str, Any]]: ...
